### ISSUE TITLE
Class constructor WinstonLoggerAdapter cannot be invoked without `new`

### ISSUE THREAD

**Issue by JacobJT** [acinader/parse-aws-firehose-logger-adapter#39]
I've just started seeing this error after updating Parse Version.  I was on 2.3.2, updated to 2.7.2.  I went and redid my updates one at a time and found that this is the (or at least, a) breaking version update.

I see this isn't really maintained anymore, but any chance you can help me resolve the issue? 

It complains on the following line of FirehoseLoggerAdapter.js, line 28:132
`var _this = _possibleConstructorReturn(this, (FirehoseLoggerAdapter.__proto__ || Object.getPrototypeOf(FirehoseLoggerAdapter)).call(this, arg));`, at the `.call(this, arg));` part.

**Comment by acinader** [comment]
Hi Jacob I just pushed version 1.3.0 for you.  Give it a try.  All of the tests pass, so it'll prolly work for you.  If not, let me know the error you get and I'll try and fix it.

**Comment by JacobJT** [comment]
Whoa, speedy fix @acinader ! I had resolved to just removing the adapter for now and finding a different persisting solution for logs later. Thanks a bunch! Throwing it back in now to see if this updated version works. You rock.

**Comment by JacobJT** [comment]
I've added the adapter back in, and am now able to build / deploy, so this issue is resolved. I'll let you know if I spot any issues with the logging itself.  Thanks again for such a quick turnaround time on this, absolutely phenomenal!
